# Generated by Django 5.2.8 on 2025-11-15 09:46

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
import stockApp.models.errorLog
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=150, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=160, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=150)),
                ('surname', models.CharField(max_length=150)),
                ('money', models.FloatField(default=0.0)),
                ('moneyAfterTransactions', models.FloatField(default=0.0)),
                ('role', models.CharField(max_length=150)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='BuyOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maxPrice', models.FloatField(default=0.0)),
                ('startAmount', models.IntegerField(default=1)),
                ('amount', models.IntegerField()),
                ('dateLimit', models.DateTimeField(db_index=True)),
                ('actual', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('active', 'ACTIVE'), ('matched', 'MATCHED'), ('expired', 'EXPIRED'), ('cancelled', 'CANCELLED')], db_index=True, default='active', max_length=16)),
                ('request_id', models.CharField(blank=True, db_index=True, max_length=64, null=True)),
                ('session_id', models.CharField(blank=True, db_index=True, max_length=64, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buy_offers', to=settings.AUTH_USER_MODEL)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buy_offers', to='stockApp.company')),
            ],
        ),
        migrations.CreateModel(
            name='Cpu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('cpuUsage', models.FloatField()),
                ('memoryUsage', models.FloatField()),
                ('containerId', models.CharField(db_index=True, max_length=64)),
                ('service', models.CharField(blank=True, db_index=True, max_length=64, null=True)),
                ('env', models.CharField(blank=True, db_index=True, max_length=32, null=True)),
            ],
            options={
                'indexes': [models.Index(fields=['containerId', 'timestamp'], name='stockApp_cp_contain_c4d5e8_idx'), models.Index(fields=['service', 'timestamp'], name='stockApp_cp_service_c809a8_idx')],
            },
        ),
        migrations.CreateModel(
            name='ErrorLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('error_id', models.CharField(db_index=True, default=stockApp.models.errorLog.gen_uuid_str, help_text='Unikalny identyfikator zdarzenia (UUID).', max_length=64, unique=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Czas wystąpienia błędu (UTC).')),
                ('level', models.CharField(choices=[('ERROR', 'ERROR'), ('WARN', 'WARN')], db_index=True, default='ERROR', help_text='Poziom błędu (ERROR/WARN).', max_length=10)),
                ('component', models.CharField(db_index=True, help_text='Moduł/serwis (np. api/matcher/db/queue).', max_length=64)),
                ('request_id', models.CharField(blank=True, db_index=True, help_text='Jeśli błąd dotyczy konkretnego żądania HTTP.', max_length=64, null=True)),
                ('parent_request_id', models.CharField(blank=True, db_index=True, help_text='Jeśli błąd dot. transakcji powiązanej z żądaniem.', max_length=64, null=True)),
                ('error_code', models.CharField(blank=True, db_index=True, help_text='Skrócony kod (np. DB.TIMEOUT, VALIDATION).', max_length=64, null=True)),
                ('message', models.CharField(help_text='Krótki opis błędu (1-2 zdania).', max_length=2048)),
                ('stack', models.TextField(blank=True, help_text='Opcjonalny stacktrace (tekst).', null=True)),
                ('context', models.JSONField(blank=True, help_text='Dodatkowy kontekst (np. parametry wejściowe).', null=True)),
                ('service_name', models.CharField(blank=True, db_index=True, help_text='Nazwa usługi (np. web/celery-worker).', max_length=64, null=True)),
                ('container_id', models.CharField(blank=True, db_index=True, help_text='Identyfikator kontenera przetwarzającego.', max_length=64, null=True)),
                ('env', models.CharField(blank=True, db_index=True, help_text='Środowisko (dev/test/prod).', max_length=32, null=True)),
                ('service_version', models.CharField(blank=True, db_index=True, help_text='Wersja serwisu (tag/commit).', max_length=64, null=True)),
            ],
            options={
                'verbose_name': 'Error Log',
                'verbose_name_plural': 'Error Logs',
                'indexes': [models.Index(fields=['timestamp'], name='stockApp_er_timesta_7208b2_idx'), models.Index(fields=['level', 'timestamp'], name='stockApp_er_level_07c1ac_idx'), models.Index(fields=['component', 'timestamp'], name='stockApp_er_compone_10bcc2_idx'), models.Index(fields=['request_id', 'timestamp'], name='stockApp_er_request_f7d36d_idx'), models.Index(fields=['service_name', 'env', 'timestamp'], name='stockApp_er_service_be3cdb_idx')],
            },
        ),
        migrations.CreateModel(
            name='RequestLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_id', models.CharField(db_index=True, max_length=64)),
                ('session_id', models.CharField(blank=True, db_index=True, max_length=64, null=True)),
                ('user_id', models.CharField(blank=True, db_index=True, max_length=64, null=True)),
                ('user_role', models.CharField(blank=True, db_index=True, max_length=64, null=True)),
                ('user_class', models.CharField(blank=True, db_index=True, max_length=64, null=True)),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('api_method', models.CharField(db_index=True, max_length=8)),
                ('endpoint', models.CharField(max_length=2048)),
                ('endpoint_group', models.CharField(blank=True, db_index=True, max_length=64, null=True)),
                ('http_status', models.IntegerField()),
                ('success', models.BooleanField(default=False)),
                ('latency_ms_total', models.FloatField()),
                ('app_time_ms', models.FloatField(blank=True, null=True)),
                ('db_time_ms', models.FloatField(blank=True, null=True)),
                ('queue_time_ms', models.FloatField(blank=True, null=True)),
                ('network_time_ms', models.FloatField(blank=True, null=True)),
                ('response_size', models.IntegerField(blank=True, null=True)),
                ('user_agent_hash', models.CharField(blank=True, max_length=64, null=True)),
                ('client_ip_hash', models.CharField(blank=True, max_length=64, null=True)),
                ('service_name', models.CharField(blank=True, db_index=True, max_length=64, null=True)),
                ('container_id', models.CharField(blank=True, db_index=True, max_length=64, null=True)),
                ('service_version', models.CharField(blank=True, db_index=True, max_length=64, null=True)),
                ('request_context', models.JSONField(blank=True, null=True)),
                ('error_context', models.JSONField(blank=True, null=True)),
                ('env', models.CharField(blank=True, db_index=True, max_length=32, null=True)),
            ],
            options={
                'verbose_name': 'Request Log',
                'verbose_name_plural': 'Request Logs',
                'indexes': [models.Index(fields=['timestamp'], name='stockApp_re_timesta_13e212_idx'), models.Index(fields=['request_id', 'timestamp'], name='stockApp_re_request_a3a0d9_idx'), models.Index(fields=['user_id', 'session_id', 'timestamp'], name='stockApp_re_user_id_5d9969_idx'), models.Index(fields=['endpoint_group', 'timestamp'], name='stockApp_re_endpoin_85ea94_idx'), models.Index(fields=['service_name', 'env', 'timestamp'], name='stockApp_re_service_352b9d_idx')],
            },
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='stockApp.company')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SellOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minPrice', models.FloatField(default=0.0)),
                ('startAmount', models.IntegerField(default=1)),
                ('amount', models.IntegerField()),
                ('dateLimit', models.DateTimeField(db_index=True)),
                ('actual', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('active', 'ACTIVE'), ('matched', 'MATCHED'), ('expired', 'EXPIRED'), ('cancelled', 'CANCELLED')], db_index=True, default='active', max_length=16)),
                ('request_id', models.CharField(blank=True, db_index=True, max_length=64, null=True)),
                ('session_id', models.CharField(blank=True, db_index=True, max_length=64, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sell_offers', to='stockApp.company')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sell_offers', to=settings.AUTH_USER_MODEL)),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sell_offers', to='stockApp.stock')),
            ],
        ),
        migrations.CreateModel(
            name='StockRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actual', models.BooleanField(default=True)),
                ('rate', models.FloatField(default=0.0)),
                ('dateInc', models.DateTimeField(db_index=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rates', to='stockApp.company')),
            ],
        ),
        migrations.CreateModel(
            name='TradeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('applicationTime', models.FloatField()),
                ('databaseTime', models.FloatField()),
                ('numberOfSellOffers', models.IntegerField()),
                ('numberOfBuyOffers', models.IntegerField()),
                ('companyIds', models.JSONField()),
                ('task_id', models.CharField(blank=True, db_index=True, max_length=64, null=True)),
                ('parent_request_id', models.CharField(blank=True, db_index=True, max_length=64, null=True)),
                ('matchedPairs', models.IntegerField(default=0)),
                ('partialFills', models.IntegerField(default=0)),
                ('rejectedOffers', models.IntegerField(default=0)),
                ('queueTimeMs', models.FloatField(default=0.0)),
                ('cycleTimeMs', models.FloatField(default=0.0)),
                ('details', models.JSONField(blank=True, null=True)),
            ],
            options={
                'indexes': [models.Index(fields=['timestamp'], name='stockApp_tr_timesta_8297a6_idx'), models.Index(fields=['task_id'], name='stockApp_tr_task_id_0a591e_idx'), models.Index(fields=['parent_request_id'], name='stockApp_tr_parent__bcaf0d_idx')],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('price', models.FloatField()),
                ('totalPrice', models.FloatField()),
                ('transacionDate', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('request_id', models.CharField(blank=True, db_index=True, max_length=64, null=True)),
                ('task_id', models.CharField(blank=True, db_index=True, max_length=64, null=True)),
                ('buyer_id_cache', models.IntegerField(blank=True, db_index=True, null=True)),
                ('seller_id_cache', models.IntegerField(blank=True, db_index=True, null=True)),
                ('buyOffer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='stockApp.buyoffer')),
                ('sellOffer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='stockApp.selloffer')),
            ],
        ),
        migrations.CreateModel(
            name='BalanceUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('changeAmount', models.FloatField()),
                ('changeType', models.CharField(choices=[('money', 'money'), ('moneyAfterTransactions', 'moneyAfterTransactions')], db_index=True, max_length=40)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('applied', models.BooleanField(db_index=True, default=False)),
                ('appliedAt', models.DateTimeField(blank=True, null=True)),
                ('request_id', models.CharField(blank=True, db_index=True, max_length=64, null=True)),
                ('session_id', models.CharField(blank=True, db_index=True, max_length=64, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='balance_updates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'applied', 'changeType'], name='stockApp_ba_user_id_501c8a_idx'), models.Index(fields=['createdAt'], name='stockApp_ba_created_99f08d_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='buyoffer',
            index=models.Index(fields=['company', 'status', 'maxPrice'], name='stockApp_bu_company_29bcf5_idx'),
        ),
        migrations.AddIndex(
            model_name='buyoffer',
            index=models.Index(fields=['company', 'actual', 'maxPrice'], name='stockApp_bu_company_196c58_idx'),
        ),
        migrations.AddIndex(
            model_name='buyoffer',
            index=models.Index(fields=['user', 'status'], name='stockApp_bu_user_id_855acc_idx'),
        ),
        migrations.AddConstraint(
            model_name='buyoffer',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gte', 0)), name='buyoffer_amount_nonneg'),
        ),
        migrations.AddConstraint(
            model_name='buyoffer',
            constraint=models.CheckConstraint(condition=models.Q(('startAmount__gte', 0)), name='buyoffer_start_amount_nonneg'),
        ),
        migrations.AddIndex(
            model_name='stock',
            index=models.Index(fields=['user', 'company'], name='stockApp_st_user_id_ef013f_idx'),
        ),
        migrations.AddConstraint(
            model_name='stock',
            constraint=models.UniqueConstraint(fields=('user', 'company'), name='uniq_user_company_stock'),
        ),
        migrations.AddIndex(
            model_name='selloffer',
            index=models.Index(fields=['company', 'status', 'minPrice'], name='stockApp_se_company_fd07be_idx'),
        ),
        migrations.AddIndex(
            model_name='selloffer',
            index=models.Index(fields=['company', 'actual', 'minPrice'], name='stockApp_se_company_bf4d2c_idx'),
        ),
        migrations.AddIndex(
            model_name='selloffer',
            index=models.Index(fields=['user', 'status'], name='stockApp_se_user_id_bf98cf_idx'),
        ),
        migrations.AddConstraint(
            model_name='selloffer',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gte', 0)), name='selloffer_amount_nonneg'),
        ),
        migrations.AddConstraint(
            model_name='selloffer',
            constraint=models.CheckConstraint(condition=models.Q(('startAmount__gte', 0)), name='selloffer_start_amount_nonneg'),
        ),
        migrations.AddIndex(
            model_name='stockrate',
            index=models.Index(fields=['company', 'dateInc'], name='stockApp_st_company_b4c1b6_idx'),
        ),
        migrations.AddIndex(
            model_name='stockrate',
            index=models.Index(fields=['company', 'actual'], name='stockApp_st_company_b66fb6_idx'),
        ),
        migrations.AddConstraint(
            model_name='stockrate',
            constraint=models.UniqueConstraint(condition=models.Q(('actual', True)), fields=('company',), name='uniq_stockrate_actual_per_company'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['transacionDate'], name='stockApp_tr_transac_cad250_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['request_id'], name='stockApp_tr_request_e778aa_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['task_id'], name='stockApp_tr_task_id_2babe6_idx'),
        ),
        migrations.AddConstraint(
            model_name='transaction',
            constraint=models.CheckConstraint(condition=models.Q(('totalPrice__gte', 0)), name='txn_totalprice_nonneg'),
        ),
    ]
